<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="58851" started-at="2017-08-10T14:04:01Z" finished-at="2017-08-10T14:05:00Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="58851" started-at="2017-08-10T14:04:01Z" finished-at="2017-08-10T14:05:00Z">
      <class name="com.experitest.auto.AndroidDemoTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.experitest.auto.AndroidDemoTest@b684286]" name="setUp" is-config="true" duration-ms="28735" started-at="2017-08-10T19:34:01Z" finished-at="2017-08-10T19:34:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="test()[pri:0, instance:com.experitest.auto.AndroidDemoTest@b684286]" name="test" duration-ms="20631" started-at="2017-08-10T19:34:30Z" finished-at="2017-08-10T19:34:50Z">
          <exception class="com.experitest.client.InternalException">
            <message>
              <![CDATA[Exception caught while executing verifyElementFound: Element //*[@text='Apps'] wasn't found]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.experitest.client.InternalException: Exception caught while executing verifyElementFound: Element //*[@text='Apps'] wasn't found
	at com.experitest.client.JavaClientInternals.executeInternally(JavaClientInternals.java:249)
	at com.experitest.client.Client.execute(Client.java:247)
	at com.experitest.client.ExecutionClient.execute(ExecutionClient.java:184)
	at com.experitest.client.Client.verifyElementFound(Client.java:2498)
	at com.experitest.auto.AndroidDemoTest.test(AndroidDemoTest.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
            </full-stacktrace>
          </exception> <!-- com.experitest.client.InternalException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.experitest.auto.AndroidDemoTest@b684286]" name="tearDown" is-config="true" duration-ms="9456" started-at="2017-08-10T19:34:50Z" finished-at="2017-08-10T19:35:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.experitest.auto.AndroidDemoTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
